using System.Globalization;
using System.Resources;

namespace WardSweep.UI.Resources;

/// <summary>
/// Typed access to the UI string table.
/// </summary>
/// <remarks>
/// <para>
/// Hand-written rather than generated by <c>PublicResXFileCodeGenerator</c>,
/// which only runs inside Visual Studio and would leave <c>dotnet build</c> on
/// a CI runner with no accessor at all.
/// </para>
/// <para>
/// Keys follow docs/17-I18N.md: <c>&lt;area&gt;.&lt;subject&gt;.&lt;detail&gt;</c>,
/// never reused across areas, and placeholders are named so a translator can
/// reorder them freely. Formatting helpers take named arguments for the same
/// reason — fragments are never concatenated.
/// </para>
/// </remarks>
public static class Strings
{
    private static readonly ResourceManager Manager =
        new("WardSweep.UI.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Gets the application name.</summary>
    public static string AppTitle => Get("app.title");

    /// <summary>Gets the pre-alpha capability statement.</summary>
    public static string AppStatusPreAlpha => Get("app.status.prealpha");

    /// <summary>Gets the title of the shell's safety-gate notice.</summary>
    public static string ShellGateTitle => Get("shell.gate.title");

    /// <summary>Gets the body of the shell's safety-gate notice.</summary>
    public static string ShellGateBody => Get("shell.gate.body");

    /// <summary>Gets the status shown before the broker handshake.</summary>
    public static string BrokerStatusDisconnected => Get("broker.status.disconnected");

    /// <summary>Gets the status shown when the catalog state is not yet known.</summary>
    public static string CatalogStatusUnknown => Get("catalog.status.unknown");

    /// <summary>Gets the status shown when no verified catalog is loaded.</summary>
    public static string CatalogStatusAbsent => Get("catalog.status.absent");

    /// <summary>
    /// Formats the connected-broker status.
    /// </summary>
    /// <param name="version">Broker executable version.</param>
    /// <param name="elevated">Whether the broker is elevated.</param>
    /// <returns>A complete sentence in the current UI culture.</returns>
    public static string BrokerStatusConnected(string version, bool elevated) =>
        Format(
            elevated ? "broker.status.connected_elevated" : "broker.status.connected",
            ("version", version));

    /// <summary>
    /// Formats the verified-catalog status.
    /// </summary>
    /// <param name="version">Catalog data version.</param>
    /// <returns>A complete sentence in the current UI culture.</returns>
    public static string CatalogStatusVerified(string version) =>
        Format("catalog.status.verified", ("version", version));

    /// <summary>
    /// Looks up a key in the current UI culture.
    /// </summary>
    /// <param name="key">The resource key.</param>
    /// <returns>The localised string, or the key itself if it is missing.</returns>
    public static string Get(string key) =>
        Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    /// <summary>
    /// Substitutes named placeholders into a localised string.
    /// </summary>
    /// <param name="key">The resource key.</param>
    /// <param name="arguments">Placeholder names and their values.</param>
    /// <returns>The localised string with placeholders replaced.</returns>
    /// <remarks>
    /// Named rather than positional so a translation may reorder them, which
    /// <see cref="string.Format(IFormatProvider, string, object?[])"/> cannot
    /// express.
    /// </remarks>
    public static string Format(string key, params (string Name, string Value)[] arguments)
    {
        ArgumentNullException.ThrowIfNull(arguments);
        var text = Get(key);
        foreach (var (name, value) in arguments)
        {
            text = text.Replace($"{{{name}}}", value, StringComparison.Ordinal);
        }

        return text;
    }
}
